### ISSUE TITLE
Regions in Ukraine are messed up

### ISSUE THREAD

**Issue by dealancer** [benkeen/polymer-country-region-selector#2]

**Comment by benkeen** [comment]
Are these incorrect? 

![screen shot 2015-02-10 at 5 26 02 pm](https://cloud.githubusercontent.com/assets/512116/6140212/f8014ab2-b149-11e4-9f03-eb9c64bd6564.png)

**Comment by benkeen** [comment]
Nevermind, I can use these: http://en.wikipedia.org/wiki/Oblasts_of_Ukraine

**Comment by benkeen** [comment]
Fixed. https://github.com/benkeen/polymer-country-region-selector/releases/tag/0.1.3

**Comment by dealancer** [comment]
Thx, it is much better now!
